### ISSUE TITLE
Solution: Combing approaches

### ISSUE THREAD

**Issue by djgrant-2** [osiegmar/github-dark-mode-bug#1]
I think you can solve this issue by combining the picture element solution with the media query solution.

Create two files, `light.svg` and `dark.svg`. 

In `light.svg` add a media query for dark mode:

```svg
<style>
    @media (prefers-color-scheme: dark) {
    .text { fill: white !important; }
    }
</style>
```

In markdown file, display both images in picture element:

```html
<picture>
   <source media="(prefers-color-scheme: dark)" srcset="dark.svg">
   <source media="(prefers-color-scheme: light)" srcset="light.svg">
  <img alt="Image" src="light.svg">
</picture>
```

I did brief test on mobile and desktop switching various settings and it seems to work consistently.

**Comment by osiegmar** [comment]
Please send a PR or fork link for further analysis.

**Comment by osiegmar** [comment]
Can't reproduce something that is consistently working. Please send a PR or fork link if you have something to share.
